FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

# Install dependencies
RUN pip install --upgrade pip --no-cache-dir
RUN pip install wandb tqdm --no-cache-dir

# Copy files
COPY . /workspace

# Set environment variables
ENV OPENBLAS_NUM_THREADS=1


# Run training
WORKDIR /workspace
ENV PYTHONPATH=/workspace
CMD ["python", "mains/replit/distill/distill_replit-3b.py"]